?"anticipo"
use anticipo EXCL
REINDEX

?"anulados"
use anulados EXCL
REINDEX

?"aplianti"
use aplianti EXCL
REINDEX

?"auxrem"
use auxrem EXCL
REINDEX

?"caja"
use caja EXCL
REINDEX

?"cajas"
use cajas EXCL
REINDEX

?"cate"
use cate EXCL
REINDEX

?"cenctas"
use cenctas EXCL
REINDEX

?"cliebon"
use cliebon EXCL
REINDEX

?"cobros"
use cobros EXCL
REINDEX

?"comart"
use comart EXCL
REINDEX

?"conpago"
use conpago EXCL
REINDEX

?"consumos"
use cajas EXCL
REINDEX

?"ctascnt"
use ctascnt EXCL
REINDEX

?"datvar"
use datvar EXCL
REINDEX

?"depo"
use depo EXCL
REINDEX

?"devol"
use devol EXCL
REINDEX

?"estcos"
use estcos EXCL
REINDEX

?"F_arti"
use f_arti EXCL
REINDEX

?"F_clie"
use f_clie EXCL
REINDEX

?"F_comp"
use f_comp EXCL
REINDEX

?"F_ctas"
use f_ctas EXCL
REINDEX

?"F_emp"
use f_emp EXCL
REINDEX

?"F_lista"
use f_lista EXCL
REINDEX

?"F_movin"
use f_movin EXCL
reindex

?"F_moviva"
use f_moviva excl
REINDEX

?"F_prov"
use f_prov EXCL
REINDEX

?"F_stok"
use f_stok EXCL
REINDEX

?"Fabren"
use fabren EXCL
REINDEX

?"Faccred"
use faccred EXCL
REINDEX

?"imput"
use imput EXCL
reindex

?"ingorden"
use ingorden excl
reindex

?"kk"
use kk excl
reindex

?"marca"
use marca excl
reindex

?"movbco"
use movbco excl
reindex

?"moviva"
use moviva excl
reindex

?"movpro"
use movpro excl
reindex

?"movsto"
use movsto excl
reindex

?"numbco"
use numbco excl
reindex

?"obsercom"
use obsercom excl
reindex

?"observa"
use observa excl
reindex

?"ordaux"
use ordaux excl
reindex

?"otra"
use otra excl
reindex

?"pagos"
use pagos excl
reindex

?"param"
use param excl
reindex

?"pcia"
use pcia excl
reindex

?"perform"
use perform excl
reindex

?"planilla"
use planilla excl
reindex

?"prescab"
use prescab excl
reindex

?"presuobs"
use presuobs excl
reindex

?"presup"
use presup excl
reindex

?"provarti"
use provarti excl
reindex

?"refer"
use refer excl
reindex

?"remprov"
use remprov excl
reindex

?"resmes"
use resmes excl
reindex

?"resumen"
use resumen excl
reindex

?"rubro"
use rubro excl 
reindex

?"sistemas"
use sistemas excl
reindex

?"sucursal"
use sucursal excl
reindex

?"talcomp"
use talcomp excl
reindex

?"talones"
use talones excl
reindex

?"temp1"
use temp1 excl
reindex

?"temp2"
use temp2 excl
reindex

?"temp3"
use temp3 excl
reindex

?"transp"
use transp excl
reindex

?"vales"
use vales excl
reindex

?"vend"
use vend excl
reindex

?"vtaaux"
use vtaaux excl
reindex

?"zonas"
use zonas excl
reindex

?"buscar"
use buscar excl
reindex